// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f6f1e8fd-7932-42c2-9f6b-0f00851a6a89",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qkEKRhCgV",
    "aws_user_pools_web_client_id": "11vcbml0dvruoeetju4tvshk06",
    "aws_content_delivery_bucket": "pettracker-avd",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://pettracker-avd.s3-website-us-east-1.amazonaws.com",
    "aws_cloud_logic_custom": [
        {
            "name": "petTrackerApi",
            "endpoint": "https://65eviqvdsa.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
