// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:90ff2ebe-8a46-496f-898e-a8300176f8e4';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '45c52f98705a465585f80c8083009b72';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '614e4c31-0786-46f9-94cb-491b5c663177';
var aws_project_name = 'Pet-Tracker';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'pettracker-mobilehub-1040120559';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
